use_frameworks!

target 'ALWStepper_Example' do
  pod 'ALWStepper', :path => '../'

  target 'ALWStepper_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
